use crate::providers::{ChatMessage, LlmError, LlmProvider, LlmStream, StreamChunk};
use futures::StreamExt;
use redact::preview;
use std::sync::Arc;
use std::time::Instant;
use tokio_stream::wrappers::ReceiverStream;
use uuid::Uuid;

mod redact;

/// Everything the ingestion worker needs to write one inference_logs row.
/// Fired once per LLM call — success OR failure.
#[derive(Debug, Clone)]
pub struct LogEvent {
    pub conversation_id: Uuid,
    pub message_id: Uuid,           // pre-generated by the handler
    pub model: String,
    pub provider: String,
    pub latency_ms: i64,
    pub input_tokens: Option<i32>,
    pub output_tokens: Option<i32>,
    pub status: String,             // "success" | "error"
    pub error_msg: Option<String>,
    pub input_preview: Option<String>,
    pub output_preview: Option<String>,
}

/// The auto-instrumentation wrapper.
/// Chat handlers call THIS, never the provider directly.
/// They get a stream of tokens and logging happens invisibly.
pub struct InstrumentedProvider {
    inner: Arc<dyn LlmProvider>,
    log_tx: tokio::sync::mpsc::Sender<LogEvent>,
}

impl InstrumentedProvider {
    pub fn new(
        inner: Arc<dyn LlmProvider>,
        log_tx: tokio::sync::mpsc::Sender<LogEvent>,
    ) -> Self {
        Self { inner, log_tx }
    }

    pub fn provider_name(&self) -> &'static str {
        self.inner.provider_name()
    }

    pub fn model_name(&self) -> String {
        self.inner.model_name().to_string()
    }

    /// Wrap one streamed completion with full metadata capture.
    pub async fn complete(
        &self,
        conversation_id: Uuid,
        message_id: Uuid,
        messages: Vec<ChatMessage>,
    ) -> Result<LlmStream, LlmError> {
        let start = Instant::now();
        let provider = self.provider_name().to_string();
        let model = self.model_name();

        // preview of what we sent (last user message, capped)
        let input_preview = messages
            .last()
            .map(|m| preview(&m.content, 500));

        let stream_result = self.inner.complete_stream(messages).await;

        // call itself failed (no stream at all) → log immediately
        let inner_stream = match stream_result {
            Ok(s) => s,
            Err(e) => {
                let event = LogEvent {
                    conversation_id,
                    message_id,
                    model,
                    provider,
                    latency_ms: start.elapsed().as_millis() as i64,
                    input_tokens: None,
                    output_tokens: None,
                    status: "error".into(),
                    error_msg: Some(redact::redact(&e.to_string())),
                    input_preview,
                    output_preview: None,
                };
                self.fire(event);
                return Err(e);
            }
        };

        // stream succeeded — forward chunks, accumulate output,
        // fire ONE log event at stream end or first error
        let (tx, rx) = tokio::sync::mpsc::channel(64);
        let log_tx = self.log_tx.clone();

        tokio::spawn(async move {
            let mut output = String::new();
            let mut usage_input: Option<i32> = None;
            let mut usage_output: Option<i32> = None;
            let mut stream = inner_stream;

            while let Some(chunk) = stream.next().await {
                match chunk {
                    Ok(StreamChunk::Token(t)) => {
                        output.push_str(&t);
                        if tx.send(Ok(StreamChunk::Token(t))).await.is_err() {
                            return; // client disconnected — stop pumping
                        }
                    }
                    Ok(StreamChunk::Done { input_tokens, output_tokens }) => {
                        usage_input = input_tokens;
                        usage_output = output_tokens;

                        fire(
                            &log_tx,
                            LogEvent {
                                conversation_id,
                                message_id,
                                model: model.clone(),
                                provider: provider.clone(),
                                latency_ms: start.elapsed().as_millis() as i64,
                                input_tokens: usage_input,
                                output_tokens: usage_output,
                                status: "success".into(),
                                error_msg: None,
                                input_preview: input_preview.clone(),
                                output_preview: Some(preview(&output, 500)),
                            },
                        );

                        let _ = tx
                            .send(Ok(StreamChunk::Done { input_tokens, output_tokens }))
                            .await;
                    }
                    Err(e) => {
                        fire(
                            &log_tx,
                            LogEvent {
                                conversation_id,
                                message_id,
                                model: model.clone(),
                                provider: provider.clone(),
                                latency_ms: start.elapsed().as_millis() as i64,
                                input_tokens: usage_input,
                                output_tokens: usage_output,
                                status: "error".into(),
                                error_msg: Some(redact::redact(&e.to_string())),
                                input_preview: input_preview.clone(),
                                output_preview: Some(preview(&output, 500)),
                            },
                        );
                        let _ = tx.send(Err(e)).await;
                        return;
                    }
                }
            }
        });

        Ok(Box::pin(ReceiverStream::new(rx)))
    }

    /// Never block the chat path on logging. If the buffer is full,
    /// drop the event with a warning instead of slowing the user down.
    fn fire(&self, event: LogEvent) {
        fire(&self.log_tx, event);
    }
}

fn fire(tx: &tokio::sync::mpsc::Sender<LogEvent>, event: LogEvent) {
    if let Err(e) = tx.try_send(event) {
        tracing::warn!(error = %e, "log channel full/closed, dropping inference log");
    }
}

fn truncate(s: &str, max: usize) -> String {
    s.chars().take(max).collect()
}

#[cfg(test)]
mod tests {
    use super::redact::{preview, redact};

    #[test]
    fn truncate_is_char_safe() {
        assert_eq!(super::truncate("नमस्ते", 3), "नमस");
    }

    #[test]
    fn sdk_preview_path_redacts() {
        let p = preview("reach me at someone@example.com", 500);
        assert!(!p.contains('@'));
        assert!(p.contains("[REDACTED:email]"));
    }

    #[test]
    fn error_msg_redacts() {
        assert_eq!(
            redact("provider 400: key sk-verysecret123 refused"),
            "provider 400: key [REDACTED:secret] refused"
        );
    }
}
